language: python
python:
  - "3.6"


#  command to install dependences
install:
  - pip install -r requirements.txt
  - pip install coveralls

#  command to run tests
script:
  - nosetests --withcoverage --cover-tests
  - coverage report

after_success:
  - coveralls
  - codecov