language: python
python:
  - "3.6"

env:
  global:
    - APP_SETTINGS=testing
    - CODECOV_TOKEN="E3kycqxPxyAPAPcs92nueuAWnNLB1dwfs"

install:
  - "pip install -r requirements.txt"

script:
  - python test_api.py
  - coveralls


after_success:
  - codecov