language: python
python:
  - "3.6"


#  command to install dependences
install:
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install coverage
  - pip install pytest 

#  command to run tests
script:
  - pytest --cov=api tests/
  - coverage report

after_success:
  - coveralls
  - codecov