language: python
python:
  - '3.6'

env:
  global:
    - APP_ENV=testing
    -SECRET_KEY='my_secret'

#  command to install dependences
install:
  - 'pip install -r requirements.txt'

#  command to run tests
script:
  - py.test --cov=tests/test_api.py

after_success:
  - coveralls
  - codecov